version: "3.8"

services:
  todo-app:
    build: ../../todo-app
    ports:
      - "5000:5000"
    volumes:
      - ../../todo-app:/app
    restart: always

  todo-frontend:
    build: ../../todo-frontend
    ports:
      - "8080:8080"
    restart: always
